name: Deploy static content to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup Pages
        uses: actions/configure-pages@v2.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: 'static/'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1.0.10
