name: shellcheck
on:
  pull_request:
    paths:
      - 'build.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.20.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
