name: stylelint
on:
  pull_request:
    paths:
      - '**.css'
      - '.github/workflows/stylelint.yml'
      - '.stylelintrc'
      - 'package.json'
      - 'package-lock.json'

jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: stylelint
        uses: reviewdog/action-stylelint@v1.30.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
