name: stylelint
on:
  pull_request:
    paths:
      - '**.css'
      - '.github/workflows/stylelint.yml'

jobs:
  shellcheck:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: stylelint
        uses: reviewdog/action-stylelint@v1.18.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
